//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyShop.Service.BabyShopWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EUser", Namespace="http://schemas.datacontract.org/2004/07/BabyShop.Data")]
    [System.SerializableAttribute()]
    public partial class EUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MLoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginJobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginMobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginPrimaryPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginRightsPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginRightsUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MLoginZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginAddress {
            get {
                return this.MLoginAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginAddressField, value) != true)) {
                    this.MLoginAddressField = value;
                    this.RaisePropertyChanged("MLoginAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginCity {
            get {
                return this.MLoginCityField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginCityField, value) != true)) {
                    this.MLoginCityField = value;
                    this.RaisePropertyChanged("MLoginCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginCompanyName {
            get {
                return this.MLoginCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginCompanyNameField, value) != true)) {
                    this.MLoginCompanyNameField = value;
                    this.RaisePropertyChanged("MLoginCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginCountry {
            get {
                return this.MLoginCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginCountryField, value) != true)) {
                    this.MLoginCountryField = value;
                    this.RaisePropertyChanged("MLoginCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginEmail {
            get {
                return this.MLoginEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginEmailField, value) != true)) {
                    this.MLoginEmailField = value;
                    this.RaisePropertyChanged("MLoginEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginFax {
            get {
                return this.MLoginFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginFaxField, value) != true)) {
                    this.MLoginFaxField = value;
                    this.RaisePropertyChanged("MLoginFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginFirstName {
            get {
                return this.MLoginFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginFirstNameField, value) != true)) {
                    this.MLoginFirstNameField = value;
                    this.RaisePropertyChanged("MLoginFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MLoginID {
            get {
                return this.MLoginIDField;
            }
            set {
                if ((this.MLoginIDField.Equals(value) != true)) {
                    this.MLoginIDField = value;
                    this.RaisePropertyChanged("MLoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginJobTitle {
            get {
                return this.MLoginJobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginJobTitleField, value) != true)) {
                    this.MLoginJobTitleField = value;
                    this.RaisePropertyChanged("MLoginJobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginLastName {
            get {
                return this.MLoginLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginLastNameField, value) != true)) {
                    this.MLoginLastNameField = value;
                    this.RaisePropertyChanged("MLoginLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginMobilePhone {
            get {
                return this.MLoginMobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginMobilePhoneField, value) != true)) {
                    this.MLoginMobilePhoneField = value;
                    this.RaisePropertyChanged("MLoginMobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginPrimaryPhone {
            get {
                return this.MLoginPrimaryPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginPrimaryPhoneField, value) != true)) {
                    this.MLoginPrimaryPhoneField = value;
                    this.RaisePropertyChanged("MLoginPrimaryPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginRightsPassword {
            get {
                return this.MLoginRightsPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginRightsPasswordField, value) != true)) {
                    this.MLoginRightsPasswordField = value;
                    this.RaisePropertyChanged("MLoginRightsPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginRightsUserID {
            get {
                return this.MLoginRightsUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginRightsUserIDField, value) != true)) {
                    this.MLoginRightsUserIDField = value;
                    this.RaisePropertyChanged("MLoginRightsUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginState {
            get {
                return this.MLoginStateField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginStateField, value) != true)) {
                    this.MLoginStateField = value;
                    this.RaisePropertyChanged("MLoginState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MLoginZip {
            get {
                return this.MLoginZipField;
            }
            set {
                if ((object.ReferenceEquals(this.MLoginZipField, value) != true)) {
                    this.MLoginZipField = value;
                    this.RaisePropertyChanged("MLoginZip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EShoppingCart", Namespace="http://schemas.datacontract.org/2004/07/BabyShop.Data")]
    [System.SerializableAttribute()]
    public partial class EShoppingCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShoppingCartActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShoppingCartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShoppingCartProductKIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ShoppingCartProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShoppingCartQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryName {
            get {
                return this.ProductCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryNameField, value) != true)) {
                    this.ProductCategoryNameField = value;
                    this.RaisePropertyChanged("ProductCategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImageURL {
            get {
                return this.ProductImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageURLField, value) != true)) {
                    this.ProductImageURLField = value;
                    this.RaisePropertyChanged("ProductImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShoppingCartActive {
            get {
                return this.ShoppingCartActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartActiveField, value) != true)) {
                    this.ShoppingCartActiveField = value;
                    this.RaisePropertyChanged("ShoppingCartActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShoppingCartId {
            get {
                return this.ShoppingCartIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartIdField, value) != true)) {
                    this.ShoppingCartIdField = value;
                    this.RaisePropertyChanged("ShoppingCartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShoppingCartProductKId {
            get {
                return this.ShoppingCartProductKIdField;
            }
            set {
                if ((this.ShoppingCartProductKIdField.Equals(value) != true)) {
                    this.ShoppingCartProductKIdField = value;
                    this.RaisePropertyChanged("ShoppingCartProductKId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShoppingCartProductPrice {
            get {
                return this.ShoppingCartProductPriceField;
            }
            set {
                if ((this.ShoppingCartProductPriceField.Equals(value) != true)) {
                    this.ShoppingCartProductPriceField = value;
                    this.RaisePropertyChanged("ShoppingCartProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShoppingCartQuantity {
            get {
                return this.ShoppingCartQuantityField;
            }
            set {
                if ((this.ShoppingCartQuantityField.Equals(value) != true)) {
                    this.ShoppingCartQuantityField = value;
                    this.RaisePropertyChanged("ShoppingCartQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BabyShopWebService.IBabyShopServiceContract")]
    public interface IBabyShopServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/ValidateUser", ReplyAction="http://tempuri.org/IBabyShopServiceContract/ValidateUserResponse")]
        BabyShop.Service.BabyShopWebService.EUser ValidateUser(BabyShop.Service.BabyShopWebService.EUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/GetUserDetails", ReplyAction="http://tempuri.org/IBabyShopServiceContract/GetUserDetailsResponse")]
        BabyShop.Service.BabyShopWebService.EUser GetUserDetails(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/CreateUser", ReplyAction="http://tempuri.org/IBabyShopServiceContract/CreateUserResponse")]
        bool CreateUser(BabyShop.Service.BabyShopWebService.EUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/InsertProductCart", ReplyAction="http://tempuri.org/IBabyShopServiceContract/InsertProductCartResponse")]
        bool InsertProductCart(BabyShop.Service.BabyShopWebService.EShoppingCart product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/GetShoppingCartIteim", ReplyAction="http://tempuri.org/IBabyShopServiceContract/GetShoppingCartIteimResponse")]
        BabyShop.Service.BabyShopWebService.EShoppingCart[] GetShoppingCartIteim(string CartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/DeleteShoppingCart", ReplyAction="http://tempuri.org/IBabyShopServiceContract/DeleteShoppingCartResponse")]
        bool DeleteShoppingCart(int productCartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyShopServiceContract/CountShoppingCartItems", ReplyAction="http://tempuri.org/IBabyShopServiceContract/CountShoppingCartItemsResponse")]
        int CountShoppingCartItems(string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBabyShopServiceContractChannel : BabyShop.Service.BabyShopWebService.IBabyShopServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BabyShopServiceContractClient : System.ServiceModel.ClientBase<BabyShop.Service.BabyShopWebService.IBabyShopServiceContract>, BabyShop.Service.BabyShopWebService.IBabyShopServiceContract {
        
        public BabyShopServiceContractClient() {
        }
        
        public BabyShopServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BabyShopServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BabyShopServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BabyShopServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BabyShop.Service.BabyShopWebService.EUser ValidateUser(BabyShop.Service.BabyShopWebService.EUser user) {
            return base.Channel.ValidateUser(user);
        }
        
        public BabyShop.Service.BabyShopWebService.EUser GetUserDetails(int userId) {
            return base.Channel.GetUserDetails(userId);
        }
        
        public bool CreateUser(BabyShop.Service.BabyShopWebService.EUser user) {
            return base.Channel.CreateUser(user);
        }
        
        public bool InsertProductCart(BabyShop.Service.BabyShopWebService.EShoppingCart product) {
            return base.Channel.InsertProductCart(product);
        }
        
        public BabyShop.Service.BabyShopWebService.EShoppingCart[] GetShoppingCartIteim(string CartId) {
            return base.Channel.GetShoppingCartIteim(CartId);
        }
        
        public bool DeleteShoppingCart(int productCartId) {
            return base.Channel.DeleteShoppingCart(productCartId);
        }
        
        public int CountShoppingCartItems(string userId) {
            return base.Channel.CountShoppingCartItems(userId);
        }
    }
}
