//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminBabyShopping.BabyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EProductCart", Namespace="http://schemas.datacontract.org/2004/07/BabyShop.Data")]
    [System.SerializableAttribute()]
    public partial class EProductCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCartKIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCartMLoginUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCartOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductCartPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCartProductKIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCartQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCartKId {
            get {
                return this.ProductCartKIdField;
            }
            set {
                if ((this.ProductCartKIdField.Equals(value) != true)) {
                    this.ProductCartKIdField = value;
                    this.RaisePropertyChanged("ProductCartKId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCartMLoginUserId {
            get {
                return this.ProductCartMLoginUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCartMLoginUserIdField, value) != true)) {
                    this.ProductCartMLoginUserIdField = value;
                    this.RaisePropertyChanged("ProductCartMLoginUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCartOrderNumber {
            get {
                return this.ProductCartOrderNumberField;
            }
            set {
                if ((this.ProductCartOrderNumberField.Equals(value) != true)) {
                    this.ProductCartOrderNumberField = value;
                    this.RaisePropertyChanged("ProductCartOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductCartPrice {
            get {
                return this.ProductCartPriceField;
            }
            set {
                if ((this.ProductCartPriceField.Equals(value) != true)) {
                    this.ProductCartPriceField = value;
                    this.RaisePropertyChanged("ProductCartPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCartProductKId {
            get {
                return this.ProductCartProductKIdField;
            }
            set {
                if ((this.ProductCartProductKIdField.Equals(value) != true)) {
                    this.ProductCartProductKIdField = value;
                    this.RaisePropertyChanged("ProductCartProductKId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCartQuantity {
            get {
                return this.ProductCartQuantityField;
            }
            set {
                if ((this.ProductCartQuantityField.Equals(value) != true)) {
                    this.ProductCartQuantityField = value;
                    this.RaisePropertyChanged("ProductCartQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategoryName {
            get {
                return this.ProductCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryNameField, value) != true)) {
                    this.ProductCategoryNameField = value;
                    this.RaisePropertyChanged("ProductCategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImageURL {
            get {
                return this.ProductImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageURLField, value) != true)) {
                    this.ProductImageURLField = value;
                    this.RaisePropertyChanged("ProductImageURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BabyService.IBabyService")]
    public interface IBabyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyService/InsertProductCart", ReplyAction="http://tempuri.org/IBabyService/InsertProductCartResponse")]
        bool InsertProductCart(AdminBabyShopping.BabyService.EProductCart product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyService/GetShoppingCartIteim", ReplyAction="http://tempuri.org/IBabyService/GetShoppingCartIteimResponse")]
        AdminBabyShopping.BabyService.EProductCart[] GetShoppingCartIteim();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBabyService/DeleteShoppingCart", ReplyAction="http://tempuri.org/IBabyService/DeleteShoppingCartResponse")]
        bool DeleteShoppingCart(int productCartId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBabyServiceChannel : AdminBabyShopping.BabyService.IBabyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BabyServiceClient : System.ServiceModel.ClientBase<AdminBabyShopping.BabyService.IBabyService>, AdminBabyShopping.BabyService.IBabyService {
        
        public BabyServiceClient() {
        }
        
        public BabyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BabyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BabyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BabyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertProductCart(AdminBabyShopping.BabyService.EProductCart product) {
            return base.Channel.InsertProductCart(product);
        }
        
        public AdminBabyShopping.BabyService.EProductCart[] GetShoppingCartIteim() {
            return base.Channel.GetShoppingCartIteim();
        }
        
        public bool DeleteShoppingCart(int productCartId) {
            return base.Channel.DeleteShoppingCart(productCartId);
        }
    }
}
